export const RECUPERER_VILLES = 'RECUPERER_VILLES';
export const RECUPERER_METEO = 'RECUPERER_METEO';
export const RECHERCHER_VILLES = 'RECHERCHER_VILLES';
export const FETCH_WEATHER_API = 'FETCH_WEATHER_API';
